runtime: python39

entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

env_variables:
  SECRET_KEY: "


automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10


handlers:
  url: /static
