runtime: python39
entrypoint: gunicorn -b :8080 app:app

env_variables:
  VAR_NAME: "VAR_VALUE"

automatic_scaling:
  min_instances: 1
  max_instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

